apiVersion: v1
kind: Service
metadata:
  name: {{ include "fcs.name" . }}
  labels:
    {{- include "fcs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "fcs.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
